# Generated by Django 4.2.8 on 2023-12-27 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Phonebook",
            fields=[
                (
                    "phonebook_id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=25)),
                ("phone_number", models.CharField(max_length=16)),
            ],
        ),
    ]
